services:
  web-app:
    container_name: dev_app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./development:/development
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    container_name: dev_database
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    container_name: dev_redis
    image: redis:alpine
    hostname: redis

  worker:
    container_name: dev_worker
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./development:/development
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - .env

  beat:
    container_name: dev_beat
    build:
      context: .
    hostname: beat
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    volumes:
      - ./development:/development
    links:
      - redis
    depends_on:
      - worker
    env_file:
      - .env

  flower:
    container_name: dev_flower
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./development:/development
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  pg_data:
    driver: local
    name: pg_data