# Generated by Django 4.2.1 on 2023-05-19 03:26

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
